import assignment as m
m.create("manish",25)
m.create("src",70,3600) 
m.read("manish")
m.read("src")
m.create("manish",50)
m.modify("manish",55)
m.delete("manish")
t1=Thread(target=(create or read or delete),args=(key_name,value,timeout))
t1.start()
t1.sleep()
t2=Thread(target=(create or read or delete),args=(key_name,value,timeout))
t2.start()
t2.sleep()
